//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoAlbertengo {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Display_T35 module using sockets 14, 13, 12 and 10 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_T35 display;
        
        /// <summary>The Camera (Premium) module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Camera camera;
        
        /// <summary>The UsbClientDP module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        /// <summary>The Joystick module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Joystick joystick;
        
        /// <summary>The SDCard module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        /// <summary>The WiFi_RS21 (Premium) module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi;
        
        /// <summary>The Ethernet_J11D (Premium) module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Ethernet_J11D ethernet;
        
        /// <summary>The Button module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button confirmButton;
        
        /// <summary>The Button module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button backButton;
        
        /// <summary>The MulticolorLed module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed ledNet;
        
        /// <summary>The MulticolorLed module using socket * of ledNet.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed ledSd;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZSpider Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZSpider)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.display = new GTM.GHIElectronics.Display_T35(14, 13, 12, 10);
            this.camera = new GTM.GHIElectronics.Camera(3);
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
            this.joystick = new GTM.GHIElectronics.Joystick(9);
            this.sdCard = new GTM.GHIElectronics.SDCard(5);
            this.wifi = new GTM.GHIElectronics.WiFi_RS21(6);
            this.ethernet = new GTM.GHIElectronics.Ethernet_J11D(7);
            this.confirmButton = new GTM.GHIElectronics.Button(11);
            this.backButton = new GTM.GHIElectronics.Button(8);
            this.ledNet = new GTM.GHIElectronics.MulticolorLed(4);
            this.ledSd = new GTM.GHIElectronics.MulticolorLed(this.ledNet.DaisyLinkSocketNumber);
        }
    }
}
